max_m_spd = 1.75
m_spd = max_m_spd;
hp = 50;
bite_delay = 0;
damage_delay = 60;
stunned = 0;
chase_player = false;
wandering = false;
wander_delay = irandom_range(300, 600);
can_see_player = false;
max_interest = 180;
interest = max_interest;